plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tm.app'
    compileSdk 30

    defaultConfig {
        applicationId "com.tm.app"
        minSdk 24
        targetSdk 30
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
